# @generated by usage-cli from ./pdf-redact.usage.kdl

# if "usage" is not installed show an error
if ! type -p usage &> /dev/null
    echo >&2
    echo "Error: usage CLI not found. This is required for completions to work in pdf-redact." >&2
    echo "See https://usage.jdx.dev for more information." >&2
    return 1
end

set _usage_spec_pdf_redact 'name pdf-redact
bin pdf-redact
about "Safe PDF redaction CLI using PyMuPDF"
flag "-h --help" help="Print help"
flag --term help="Term to redact. Repeat for multiple terms." var=#true {
    arg <value>
}
flag --regex-term help="Regex pattern to redact. Repeat for multiple patterns." var=#true {
    arg <pattern>
}
flag --terms-file help="File with one term per line." var=#true {
    arg <file>
}
flag --source help="Path to a single PDF file or a directory containing PDFs." {
    arg <path>
}
flag --output-path help="Directory where redacted PDFs will be written." {
    arg <dir>
}
flag "-r --recursive" help="Recursively scan subdirectories when source is a directory."
flag --case-insensitive help="Match terms case-insensitively."
flag --dry-run help="Scan and report matches without writing output files."
flag --verify-on-match help="Behavior when verification still finds redacted terms in output." {
    arg <mode> {
        choices warn fail
    }
}
cmd completion help="Print shell completion script" {
    arg <shell> help="Shell type" {
        choices bash fish zsh
    }
}
'
set -l tmpdir (if set -q TMPDIR; echo $TMPDIR; else; echo /tmp; end)
set -l spec_file "$tmpdir/usage__usage_spec_pdf_redact.spec"
echo $_usage_spec_pdf_redact > "$spec_file"

set -l tokens
if commandline -x >/dev/null 2>&1
    complete -xc pdf-redact -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -xpc) (commandline -t))"
else
    complete -xc pdf-redact -a "(command usage complete-word --shell fish -f \"$spec_file\" -- (commandline -opc) (commandline -t))"
end
