#compdef pdf-redact
# @generated by usage-cli from ./pdf-redact.usage.kdl
local curcontext="$curcontext"

_pdf_redact() {
  typeset -A opt_args
  local curcontext="$curcontext" cache_policy

  if ! type -p usage &> /dev/null; then
      echo >&2
      echo "Error: usage CLI not found. This is required for completions to work in pdf-redact." >&2
      echo "See https://usage.jdx.dev for more information." >&2
      return 1
  fi

  local spec_file="${TMPDIR:-/tmp}/usage__usage_spec_pdf_redact.spec"
  cat > "$spec_file" <<'__USAGE_EOF__'
name pdf-redact
bin pdf-redact
about "Safe PDF redaction CLI using PyMuPDF"
flag "-h --help" help="Print help"
flag --term help="Term to redact. Repeat for multiple terms." var=#true {
    arg <value>
}
flag --regex-term help="Regex pattern to redact. Repeat for multiple patterns." var=#true {
    arg <pattern>
}
flag --terms-file help="File with one term per line." var=#true {
    arg <file>
}
flag --source help="Path to a single PDF file or a directory containing PDFs." {
    arg <path>
}
flag --output-path help="Directory where redacted PDFs will be written." {
    arg <dir>
}
flag "-r --recursive" help="Recursively scan subdirectories when source is a directory."
flag --case-insensitive help="Match terms case-insensitively."
flag --dry-run help="Scan and report matches without writing output files."
flag --verify-on-match help="Behavior when verification still finds redacted terms in output." {
    arg <mode> {
        choices warn fail
    }
}
cmd completion help="Print shell completion script" {
    arg <shell> help="Shell type" {
        choices bash fish zsh
    }
}
__USAGE_EOF__
  _arguments "*: :(($(command usage complete-word --shell zsh -f "$spec_file" -- "${words[@]}" )))"
  return 0
}

if [ "$funcstack[1]" = "_pdf_redact" ]; then
    _pdf_redact "$@"
else
    compdef _pdf_redact pdf-redact
fi

# vim: noet ci pi sts=0 sw=4 ts=4
